name: Deploy

on:
  push:
    branches:
      - main  # The branch to deploy on merge

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # SSH into the server and run deployment commands
      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /root/projects/group-write
          git pull origin main
          cd ./client
          npm install
          npx webpack
          cd ../server
          go build
          cd ..
          systemctl restart group-write.fe.service
          systemctl restart group-write.be.service
          EOF
